lib/donegood_web/router.ex
defmodule DonegoodWeb.Router do
  use DonegoodWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug NavigationHistory.Tracker
  end

  # see https://evalcode.com/simple-guardian/
  pipeline :browser_auth do
    plug Donegood.Auth.Pipeline
    plug :set_user_as_asset
  end

  pipeline :api do
    plug :accepts, ["json"]

  end

  scope "/auth", DonegoodWeb do
    pipe_through [:browser]

    get "/sign-in", PageController, :signin
    get "/logout", AuthController, :logout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
  end

  scope "/", DonegoodWeb do
    pipe_through [:browser]

    get "/:username/vs/:other_username", CompetitionController, :fixture
    get "/welcome", PageController, :welcome
    get "/about/faq", PageController, :faq

  end

  scope "/", DonegoodWeb do
    pipe_through [:browser, :browser_auth]

    get "/", PageController, :index

    resources "/users", UserController, only: [:edit, :update, :show]
    resources "/deeds", DeedController do
      resources "/comments", CommentController
    end
  end

  scope "api", DonegoodWeb do
    pipe_through(:api)

    resources "/deeds", DeedController

  end

  # Other scopes may use custom stacks.
  # scope "/api", DonegoodWeb do
  #   pipe_through :api
  # end
  def set_user_as_asset(conn, _) do
    user = conn |> Donegood.Auth.Guardian.Plug.current_resource
    IO.inspect user
    assign(conn, :current_user, user)
  end
end

lib/donegood/competitions/competitions.ex
defmodule Donegood.Competitions do
  alias Donegood.Deeds.Deed
  use Timex
  import Ecto.Query, warn: false
  alias Donegood.Repo
  alias Donegood.Deeds

  def start_dates do
    Interval.new(from: ~D[2018-11-23], step: [weeks: 1], until: Timex.now)
    |> Enum.reverse
  end

  def weekly_leaderboard_scores do
    query =
      from deed in Deed,
        join: user in assoc(deed, :user),
        select: [user.name, sum(deed.score), deed.when, deed.id, deed.user_id],
        group_by: [deed.when, deed.user_id, user.name, deed.id, deed.score]
    Repo.all(query)
  end

  def league_table_row(user, me) do
    start_dates = Donegood.Competitions.start_dates()
    weekly_results =
      start_dates
      |> Enum.map(fn start_date ->
        weekly_result(start_date, me, user)
      end)
    this_week = List.first(start_dates)
    four_weeks_ago = start_dates |> Enum.at(5)
    this_week_fixture = %{
      points: Deeds.score_for_period(this_week, user),
      acts: Deeds.deeds_for_period(this_week, user) |> Enum.count
    }
    all_time_fixture = fixture_since(
      List.last(start_dates),
      user,
      weekly_results |> List.delete( List.first(weekly_results) )
    )
    %Donegood.Competitions.LeagueTableRow{
      user: user,
      this_week: this_week_fixture,
      last_4_weeks: fixture_since(
        four_weeks_ago,
        user,
        weekly_results |> Enum.filter(fn week ->
          NaiveDateTime.compare(week.start_date, four_weeks_ago) == :gt
          and NaiveDateTime.compare(this_week, week.start_date) == :gt
        end)
      ),
      all_time:
        all_time_fixture
        |> Map.put(:points, all_time_fixture.points + this_week_fixture.points)
        |> Map.put(:acts, all_time_fixture.acts + this_week_fixture.acts)
    }
  end

  defp fixture_since(start_date, user, weekly_results) do
    IO.inspect(start_date: start_date, weekly_results: weekly_results)
    %{
      points: weekly_results |> Enum.map(fn week -> week.their_points end) |> Enum.sum,
      acts: weekly_results |> Enum.map(fn week -> week.their_acts_count end) |> Enum.sum,
      wins: weekly_results |> Enum.map(fn week -> if week.result == :win, do: 1, else: 0 end )|> Enum.sum,
      losses: weekly_results |> Enum.map(fn week -> if week.result == :loss, do: 1, else: 0 end )|> Enum.sum,
      draws: weekly_results |> Enum.map(fn week -> if week.result == :draw, do: 1, else: 0 end )|> Enum.sum
    }
  end

  defp weekly_result(start_date, me, them) do
    my_points = Deeds.score_for_period(start_date, me)
    their_points = Deeds.score_for_period(start_date, them)

    result = cond do
      (NaiveDateTime.compare(me.inserted_at, start_date) == :gt or NaiveDateTime.compare(them.inserted_at, start_date) == :gt) -> :not_applicable
      (my_points > their_points) -> :win
      (my_points < their_points) -> :loss
      true -> :draw
    end
    %Donegood.Competitions.WeeklyResult{
      start_date: start_date,
      result: result,
      my_points: my_points,
      my_acts_count: Deeds.deeds_for_period(start_date, me) |> Enum.count,
      their_points: their_points,
      their_acts_count: Deeds.deeds_for_period(start_date, them) |> Enum.count
    }
  end

end

lib/donegood/competitions/league_table_fixture.ex
defmodule Donegood.Competitions.LeagueTableFixture do
  defstruct points: 0, acts: 0, wins: 0, losses: 0, draws: 0 
end

lib/donegood/competitions/league_table_row.ex
defmodule Donegood.Competitions.LeagueTableRow do
  alias Donegood.Competitions.LeagueTableFixture
  defstruct user: %Donegood.Accounts.User{}, 
            this_week: %LeagueTableFixture{},
            last_4_weeks: %LeagueTableFixture{},
            all_time: %LeagueTableFixture{}
end

lib/donegood/competitions/weekly_result.ex
defmodule Donegood.Competitions.WeeklyResult do
  defstruct start_date: nil, result: :draw, my_points: 0, their_points: 0, my_acts_count: [], their_acts_count: []
end

lib/donegood_web/controllers/competition_controller.ex
defmodule DonegoodWeb.CompetitionController do
  use DonegoodWeb, :controller
  alias Donegood.Accounts

  def fixture(conn, params) do
    user = Accounts.get_user_by_username!(params["username"])
    other_user = Accounts.get_user_by_username!(params["other_username"])
    render(conn, "fixture.html", competing_users: [user, other_user])
  end
end

lib/donegood_web/views/competition_view.ex
defmodule DonegoodWeb.CompetitionView do
  use DonegoodWeb, :view

end

lib/donegood_web/templates/competition/_leaderboard.html.eex
<h2>
  <%= Enum.at(@users,0).name %> vs <%= Enum.at(@users,1).name %>
  <span class="pull-right">
    <a href="/deeds/new" class="button">
      ＋Add
    </a>
  </span>
</h2>
<table>
  <tr>
    <th></th>
    <%= for user <- @users do %>
      <th><%= user.name %></th>
    <% end %>
  </tr>
<%= for start_date <- @start_dates do %>
  <% weeks = Timex.diff(Timex.now, start_date, :weeks) %>
  <tr>
    <th><%= if (weeks == 0), do: "This week", else: if weeks == 1, do: "Last week", else: Kernel.inspect(weeks) <> " weeks ago" %></th>
    <%= for user <- @users do %>
      <td>
        <h3><%= Donegood.Deeds.score_for_period(start_date, user) %></h3>
        <ul>
          <%= for deed <- Donegood.Deeds.deeds_for_period(start_date,user) do %>
            <li>
              <strong><%= deed.score %></strong>: <%= deed.title%>
              <%= if deed.repeats, do: "♺", else: "" %>
              <%= link( inspect(Enum.count(deed.comments)) <> " comment" <> if(Enum.count(deed.comments) == 1, do: "", else: "s"), to:  Routes.deed_path(@conn, :show, deed)) %>
            </li>
          <% end %>
        </ul>
      </td>
    <% end %>
  </tr>
<% end %>
</table>

lib/donegood_web/templates/competition/fixture.html.eex
<%= render "_leaderboard.html",
  conn: @conn,
  weekly_leaderboard_scores: Donegood.Competitions.weekly_leaderboard_scores,
  users: @competing_users,
  start_dates: Donegood.Competitions.start_dates
   %>
  <%# render "_overview.html", conn: @conn, current_user: @current_user %>